name: 🏗️ Build and 🚀 Release Docker Image with pgvector

on:
  push:
    tags:
      - 'v*'
    paths:
      - 'vector/**'
      - '.github/workflows/release.yml'
  workflow_dispatch:

env:
  DOCKER_IMAGE: ${{ github.repository }}-vector
  PLATFORMS: linux/amd64,linux/arm64
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 🔑 Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: 🏷️ Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=SyneHQ PostgreSQL with pgvector
            org.opencontainers.image.description=Enterprise-grade Vector Database Solution
            org.opencontainers.image.vendor=SyneHQ
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: vector/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
